//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PathIdentifyEquipDemoDBEntities : DbContext
    {
        public PathIdentifyEquipDemoDBEntities()
            : base("name=PathIdentifyEquipDemoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_DeviceStatusLog> T_DeviceStatusLog { get; set; }
        public DbSet<T_PathIdentifyEquip> T_PathIdentifyEquip { get; set; }
        public DbSet<T_ReceiveData> T_ReceiveData { get; set; }
        public DbSet<T_DataDict> T_DataDict { get; set; }
    }
}
