//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ReceiveData
    {
        public int Id { get; set; }
        public int EquipId { get; set; }
        public string VehPlateNo { get; set; }
        public string VehPlateColor { get; set; }
        public int VehicleSpeed { get; set; }
        public System.DateTime ReachTime { get; set; }
        public Nullable<double> VehicleLength { get; set; }
        public string ImageAllPath { get; set; }
        public string ImageNearPath { get; set; }
        public string ImagePlateNoPath { get; set; }
        public string ImageBinPlateNoPath { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
